### PR TITLE
Development

### PR DESCRIPTION
**Pull request by CDacres**
Added tests for each service (tests in separate contexts).
Added gemfile.

### CODE REVIEW

**Comment by CDacres** [comment]
Need to update readme further.

**Comment by CDacres** [comment]
Added information on how to run tests to readme.

**Review by kcorn1982 — CHANGES_REQUESTED** [review]
Remove the debug code from the service object please.

**Comment by CDacres** [comment]
Debug code removed as requested.

**Review by kcorn1982 — APPROVED** [review]

**Pull request merged**
